# Generated by Django 5.1.7 on 2025-03-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SCHOOL', 'School'), ('SPONSOR', 'Sponsor')], default='ADMIN', max_length=20),
        ),
    ]
