# Generated by Django 5.1.7 on 2025-03-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('STAFFStaff', 'Staff'), ('ADMIN', 'Admin'), ('SCHOOL', 'School'), ('SPONSOR', 'Sponsor')], default='STAFFStaff', max_length=20),
        ),
    ]
