# Generated by Django 5.1.7 on 2025-03-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SCHOOL', 'School'), ('SPONSOR', 'Sponsor'), ('GUEST', 'Guest')], default='GUEST', max_length=20),
        ),
    ]
