# Generated by Django 5.1.7 on 2025-03-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('SCHOOL', 'School'), ('SPONSOR', 'Sponsor'), ('ADMIN', 'Admin')], default='GUEST', max_length=20),
        ),
    ]
