# Generated by Django 5.1.7 on 2025-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorrepresentative',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/school/representative/'),
        ),
    ]
