# Generated by Django 5.1.7 on 2025-03-16 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_anonymousdonation_funding_campaign_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousdonation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='anonymousdonation',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='anonymousdonation',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='sponsorrepresentative',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sponsorrepresentative',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='sponsorrepresentative',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
