# Generated by Django 5.1.7 on 2025-03-11 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_school_fundingcampaign_schools_and_more'),
        ('sponsor', '0002_alter_sponsorrepresentative_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('funding_campaign', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='school.fundingcampaign')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='sponsor.sponsor')),
            ],
        ),
    ]
