# Generated by Django 5.1.7 on 2025-03-11 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_fundingcampaign_donations'),
        ('sponsor', '0004_alter_donation_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='funding_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='school.fundingcampaign'),
        ),
    ]
