# Generated by Django 5.1.7 on 2025-03-17 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_anonymousdonation_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymousdonation',
            name='created_by',
        ),
    ]
