# Generated by Django 5.1.7 on 2025-03-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_remove_sponsor_representative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='amount',
        ),
    ]
