# Generated by Django 5.1.7 on 2025-03-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0007_remove_sponsor_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/sponsor/'),
        ),
        migrations.AlterField(
            model_name='sponsorrepresentative',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/sponsor/representative/'),
        ),
    ]
