# Generated by Django 5.1.7 on 2025-03-23 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_fundingcampaign_sponsors'),
        ('sponsor', '0007_alter_anonymousdonation_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='sponsor',
            new_name='sponsor_org',
        ),
        migrations.RenameField(
            model_name='sponsorrepresentative',
            old_name='sponsor',
            new_name='sponsor_company',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='sponsorrepresentative',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sponsorrepresentative',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='sponsorrepresentative',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sponsorrepresentative',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='anonymousdonation',
            name='funding_campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='anonymous_donations', to='school.fundingcampaign'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='funding_campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='school.fundingcampaign'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sponsor.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sponsor.basemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsorrepresentative',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sponsor.basemodel'),
            preserve_default=False,
        ),
    ]
