# Generated by Django 5.1.7 on 2025-03-14 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_student_email_student_parent_consent'),
        ('sponsor', '0008_sponsor_photo_alter_sponsorrepresentative_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('funding_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anonymous_donations', to='school.fundingcampaign')),
            ],
        ),
    ]
