# Generated by Django 5.1.7 on 2025-03-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0009_anonymousdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousdonation',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
