# Generated by Django 5.1.7 on 2025-03-16 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingcampaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fundingcampaign',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='fundingcampaign',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='schooldocument',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='schooldocument',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='schooldocument',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='schoolimage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='schoolimage',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='schoolimage',
            name='last_modified',
        ),
        migrations.AlterField(
            model_name='representative',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
