# Generated by Django 5.1.7 on 2025-03-11 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_representative_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='photo',
            field=models.ImageField(upload_to='images/school/representative/'),
        ),
        migrations.AlterField(
            model_name='schooldocument',
            name='document',
            field=models.FileField(upload_to='documents/school/'),
        ),
        migrations.AlterField(
            model_name='schoolimage',
            name='image',
            field=models.ImageField(upload_to='images/school/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='images/school/students/'),
        ),
        migrations.CreateModel(
            name='FundingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='school.school')),
            ],
        ),
    ]
