# Generated by Django 5.1.7 on 2025-03-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_fundingcampaign_created_by_and_more'),
        ('sponsor', '0007_alter_anonymousdonation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingcampaign',
            name='sponsors',
            field=models.ManyToManyField(blank=True, null=True, related_name='funding_campaigns', to='sponsor.sponsor'),
        ),
    ]
