# Generated by Django 5.1.7 on 2025-03-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_representative_photo_and_more'),
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingcampaign',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fundingcampaign',
            name='sponsor',
            field=models.ManyToManyField(related_name='funding_campaigns', to='sponsor.sponsor'),
        ),
        migrations.AddField(
            model_name='fundingcampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='fundingcampaign',
            name='school',
        ),
        migrations.AddField(
            model_name='fundingcampaign',
            name='school',
            field=models.ManyToManyField(blank=True, related_name='funding_campaigns', to='school.school'),
        ),
    ]
