# Generated by Django 5.1.7 on 2025-03-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_fundingcampaign_end_date_fundingcampaign_sponsor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingcampaign',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSE', 'close')], default='OPEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='fundingcampaign',
            name='reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
