# Generated by Django 5.1.7 on 2025-03-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_fundingcampaign_status_alter_fundingcampaign_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/school/representative/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/school/students/'),
        ),
    ]
