# Generated by Django 5.1.7 on 2025-03-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_representative_photo_alter_student_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingcampaign',
            old_name='school',
            new_name='schools',
        ),
        migrations.RenameField(
            model_name='fundingcampaign',
            old_name='sponsor',
            new_name='sponsors',
        ),
    ]
