# Generated by Django 5.1.7 on 2025-03-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_rename_school_fundingcampaign_schools_and_more'),
        ('sponsor', '0004_alter_donation_sponsor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representative',
            options={'verbose_name': 'Schools Representative'},
        ),
        migrations.RemoveField(
            model_name='fundingcampaign',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='fundingcampaign',
            name='donations',
            field=models.ManyToManyField(blank=True, related_name='funding_campaigns', to='sponsor.donation'),
        ),
    ]
