# Generated by Django 5.1.7 on 2025-03-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_representative_options_and_more'),
        ('sponsor', '0004_alter_donation_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingcampaign',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='funding_campaigns', to='sponsor.sponsor'),
        ),
    ]
