# Generated by Django 5.1.7 on 2025-03-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_fundingcampaign_sponsors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingcampaign',
            name='donations',
        ),
    ]
