# Generated by Django 5.1.7 on 2025-03-11 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_remove_fundingcampaign_donations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingcampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
