# Generated by Django 5.1.7 on 2025-03-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_fundingcampaign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingcampaign',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
