# Generated by Django 5.1.7 on 2025-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_fundingcampaign_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingcampaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
