# Generated by Django 5.1.7 on 2025-03-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_student_student_class_student_student_story_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_consent',
            field=models.FileField(blank=True, upload_to='documents/school/parent_consent/'),
        ),
    ]
